### ISSUE TITLE
formula is not backwards compatible

### ISSUE THREAD

**Issue by heimdull** [saltstack-formulas/keepalived-formula#15]
After your refactoring you are still using the plural vrrp_instances vrrp_scripts in the pillar.examples but in the config.jinja its looking for vrrp_script and vrrp_instance. 

I'm thinking that the pillar.examples is correct since you can have multiple scripts and instances

**Comment by jebas** [comment]
I've created a pull request  #16 to correct the pillar issue, but I don't think that it is worth the effort to make the present system backwards compatible.  If you follow to https://github.com/saltstack-formulas/keepalived-formula/blob/2ed31952085e9126e1f1efe99f13de3f3395ff8e/keepalived/templates/keepalived.jinja you will see that the original version of the template was a hard coded solution.  Only certain values were looked for in a specific order, and some of keepalived's features were just not available.

The new version of the template follows the pattern that they used to form their configs.  None of the values are hard coded, and all of the features are available.  There's even a test suite for when they do make changes in their configuration format.  

I don't think that making these two template systems work together is really worth the effort.  Maybe I should have created an ng version like they are doing in some of the other formulas, but I did not think of it at the time.  Additionally, it only take minor modifications to the old pillars to make it work with the new system.

**Comment by n-rodriguez** [comment]
> it only takes minor modifications to the old pillars to make it work with the new system.

:+1: 

> I'm thinking that the pillar.examples is correct since you can have multiple scripts and instances

Yes you can, but actually the pillar key is used to build sections name in `keepalived.conf`.
Example :

```
virtual_server 192.168.200.100 443 {
  delay_loop 6
  lb_algo rr
  lb_kind NAT
  nat_mask 255.255.255.0
  persistence_timeout 50
  protocol TCP
  real_server 192.168.201.100 443 {
    SSL_GET {
      url {
        digest ff20ad2481f97b1754ef3e12ecd3a9cc
        path /
      }
      url {
        digest 9b3a0c85a887a256d6939da88aabd8cd
        path /mrtg/
      }
      connect_timeout 3
      nb_get_retry 3
      delay_before_retry 3
    }
    weight 1
  }
}
```
I think it would break keepalived config if the pillar key were pluralized.
Adding some logic to singularize pillar key is IMHO too much.

This issue can be closed.

**Comment by jebas** [comment]
Sorry, but I stopped maintaining that my saltstack formulas a few years
back.  Though I like the eventing engine in salt, I am not using it in my
present projects, and I don't have enough time to maintain something I am
not presently using.  Please feel free to fork the formula if it is useful
to you.

Jeff Baskin
